name: Build firmware
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container: 
      image: nordicplayground/nrfconnect-sdk:v2.4-branch
      options: --user root
    steps:    
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Zephyr Binaries
        run:  |
          west build --board zswatch_nrf5340_cpuapp app
          mkdir build/zephyr/zephyr.elf zswatch_build/zephyr.elf
      - name: Archive build results
        uses: actions/upload-artifact@v2
        with:
            name: zswatch-build
            path: |
                zswatch_build/zephyr.elf
